create table if not exists ct_user (
    id int8 generated by default as identity,
    login varchar(255),
    full_name varchar(255),
    password varchar(255),
    primary key (id),
    unique(login)
 );