create table if not exists ct_investor (
    id int8 generated by default as identity,
    funds float8,
    user_id int8,
    primary key (id),
    constraint FKk1kty64phf4j7enysv06fnh6w foreign key (user_id) references ct_user
);