create table if not exists ct_portfolio (
    id int8 generated by default as identity,
    name varchar(255),
    investor_id int8,
    primary key (id),
    constraint FKee6j16nuaaarme5hxc06gn1yw foreign key (investor_id) references ct_investor
);