create table if not exists ct_operation (
    id int8 generated by default as identity,
    coin_id int8,
    coin_name varchar(255),
    coin_price float8,
    coin_symbol varchar(255),
    date date,
    qtd_coin float8,
    total_value float8,
    type int4,
    portfolio_id int8,
    primary key (id),
    constraint FKgf51r7ufrjlgr2a43lr5j86y8 foreign key (portfolio_id) references ct_portfolio on delete cascade
);